name: PHPStan & PHP-CS-Fixer Analysis

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v2

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # You can specify the PHP version you need

      # Step 3: Install PHP dependencies (composer packages like PHPStan and PHP-CS-Fixer)
      - name: Install Composer dependencies
        run: composer install

      # Step 4: Run PHPStan (static analysis)
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --level=max

      # Step 5: Run PHP-CS-Fixer (linter)
      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
